feat: Add author, department
alyf-de/erpnext_germany pull request #49
Opened 2024-10-11 14:28 UTC by 0xD0M1M0

- Adress first points out of #46 :
  - Author & Department added
~~- Add Jinja to content~~
  - Sort Recipient & Sender columns

2024-10-24 17:55 UTC, barredterra requested changes

2024-10-24 17:55 UTC, barredterra commented on erpnext_germany/erpnext_germany/doctype/business_letter/business_letter.json
> +   "options": "Jinja",
This does nothing

2024-10-24 17:55 UTC, barredterra commented on erpnext_germany/erpnext_germany/doctype/business_letter/business_letter.json
> +   "reqd": 1
This should not be mandatory because it improves backwards compatibility and making it mandatory is an easy customization.

2024-10-24 18:07 UTC, 0xD0M1M0 commented on erpnext_germany/erpnext_germany/doctype/business_letter/business_letter.json
> +   "options": "Jinja",
ok, leaving me confused. I tried this:

{{ contact.first_name }}
{{ department }}

Case 1: No "Options: Jinja" -> no replacement of strings
Case 2: "Options: Jinja" -> "contact.first_name" is replaced correctly, department is not replaced

2024-10-24 20:59 UTC, barredterra commented on erpnext_germany/erpnext_germany/doctype/business_letter/business_letter.json
> +   "options": "Jinja",
You're probably conflating different errors here

2024-11-06 16:03 UTC, 0xD0M1M0 commented on erpnext_germany/erpnext_germany/doctype/business_letter/business_letter.json
> +   "options": "Jinja",
Due to testing issues, I currently cannot implement the additional Jinja get_context.

2024-11-25 07:54 UTC, 0xD0M1M0 commented
Removed Jinja and the try to add additional fields in the text box (not urgent, will look at it later.). PR is ready for review.

2025-02-19 21:17 UTC, barredterra approved these changes

2025-02-19 21:18 UTC, merged